SELECT
	grr.*
from
	GCCC_CUSTOMER_TYPE gct
inner join GCCD_RELATIONSHIP gr on
	gct.COD_DEVELOP = gr.CUSTOMER_TYPE
INNER join GCCOM_PAYMENT_FORM gpf on
	gr.ID_RELATIONSHIP = gpf.ID_CUSTOMER
INNER JOIN
GCCOM_CONTRACTED_SERVICE gcs on
	gpf.ID_PAYMENT_FORM = gcs.ID_PAYMENT_FORM
INNER join GCCOM_SECTOR_SUPPLY gss on
	gcs.ID_SECTOR_SUPPLY = gss.ID_SECTOR_SUPPLY
INNER JOIN GCGT_RE_MEASUREMENT_POINT grmp on
	gss.ID_SECTOR_SUPPLY = grmp.ID_SECTOR_SUPPLY
INNER join GCGT_RE_READING grr on
	grmp.ID_MEASURING_POINT = grr.ID_MEASURING_POINT
where
	NAME_TYPE = 'Commercial'